blank_issues_enabled: false
contact_links:
  - name: 💡 General questions
    url: https://discord.com/invite/feTf9x3ZSB
    about: Have general questions about how to use Gradio? Please ask in our community Discord for quicker responses
